### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by vemel** [conda-forge/boto3-feedstock#468]
I am currently working on a project that automatically generates type annotations for boto3 and all services: https://github.com/vemel/mypy_boto3

It is compatible with mypy, VSCode and PyCharm

### How to install

```bash
# pip install 'boto3-stubs[<list of boto3 services>]==<boto3_version>.x'
pip install 'boto3-stubs[ec2,s3]=1.11.2.1'

# optionally rebuild index of installed service packages
# mypy_boto3
```

I recommend adding only most popular services because PyCharm can be slow when you have 15+ services installed.

Let me know what you think.

**Comment by tkelman** [comment]
I don't think this issue is relevant for the conda-forge packaging of boto3. Since your type annotations are released on pypi on their own, you can pursue packaging them in conda-forge as a new package within the staged-recipes repository.

**Comment by vemel** [comment]
Thank you!

**Comment by maresb** [comment]
Greetings @vemel,

@thewchan and I have been working on conda-forge packages for your project. See:

https://github.com/conda-forge/boto3-stubs-feedstock
https://github.com/conda-forge/mypy-boto3-s3-feedstock
https://github.com/conda-forge/staged-recipes/pull/14915
https://github.com/conda-forge/staged-recipes/pull/14923

Could I add you as a maintainer for these? Thank you so much for creating these stubs!

**Comment by vemel** [comment]
Sure! Thank you a lot!

**Comment by vemel** [comment]
@maresb Sure! Thank you, looks awesome!
