### ISSUE TITLE
have the bot only issue PRs when the recipe is solvable

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/boto3-feedstock#574]
@conda-forge/boto3 
The bot has a new feature, if you put
```yaml
bot:
  check_solvable: True
```
into the `conda-forge.yml` the bot won't issue a version bump PR until all the required dependencies are available. In this case that would mean the bot wouldn't open a version bump to boto3 until the required botocore version is installable. This might reduce some noise from the bot, and would make automerge work properly if you choose to take that approach. This feature is still in beta, so if you run into issues let the bot team know.

**Comment by tkelman** [comment]
I don't really mind it opening a PR that will fail initially. On minor version changes occasionally these offsets https://github.com/conda-forge/boto3-feedstock/blob/master/recipe/meta.yaml#L6-L8 would need to change, and that's easier to do if the bot opens a slightly-wrong PR than if it doesn't open anything.

Automerge seems dangerous and flawed to me, until an entire recipe is faithfully generated from the contents of setup.py - the version requirements of other dependencies get missed unless someone is manually keeping an eye on them.
